pages:
posts:
  'Person':
    options:
      name: people
      label: People
    fields:
      name:
        first:
          type: text
          label: First Name
        middle:
          type: text?
          label: Middle Name
        last:
          type: text
          label: Last Name
      title:
        type: taxonomy
        ref: Level
      contact:
        type: group
        label: Contact Info
        fields:
          email: text
          phone: text?
      details:
        type: tab
      bio:
        main: wysiwyg
        additional: wysiwyg?
    taxonomies:
      - Level
  'BlogPost':
    authors: Person[]
    content: wysiwyg
    # taxonomies:
    #   - tags

