version: '3'
services:

  # api:
  #   image: node:10
  #   environment:
  #     DB_HOST: db
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - ./api/src:/src
  #     - ./api/package.json:/package.json
  #     - ./api/package-lock.json:/package-lock.json
  #   command: [ 'npm', 'run', 'docker' ]

  db: # Database used by Wordpress
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  yaml: # Converts YAML to Wordpress JSON
    build: ./cms/parser
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SHELL=/bin/bash
    volumes:
      - ./cms/parser/src:/usr/src/app/src
      - ./cms/parser/package.json:/usr/src/app/package.json
      - ./config.yml:/usr/config.yml
      - ./cms/parser/dist:/usr/src/app/dist

  wordpress: # PHP server running wordpress
    build: ./cms
    links:
      - db:mysql
    ports:
      - 8080:8080
    # volumes:
    #   - ./cms/parser/dist/acf-json:/var/www/html/wp-content/themes/headless-theme/acf-json
    environment:
      MYSQL_ROOT_PASSWORD: password
