version: '3'
services:

  api:
    image: node:10
    environment:
      DB_HOST: db
    ports:
      - 4000:4000
    volumes:
      - ./api/src:/src
      - ./api/package.json:/package.json
      - ./api/package-lock.json:/package-lock.json
    command: [ 'npm', 'run', 'docker' ]

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    build:
      context: ./cms
    links:
      - db:mysql
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: password
