const post = ({
  name,
  label,
  singular_label: singular,
  hierarchical = false
}) => ({
  name,
  label,
  singular_label: singular,
  description: '',
  public: 'true',
  publicly_queryable: 'true',
  show_ui: 'true',
  show_in_nav_menus: 'true',
  show_in_rest: 'true',
  rest_base: '',
  rest_controller_class: '',
  has_archive: 'false',
  has_archive_string: '',
  exclude_from_search: 'false',
  capability_type: 'post',
  hierarchical: String(hierarchical),
  rewrite: 'true',
  rewrite_slug: '',
  rewrite_withfront: 'true',
  query_var: 'true',
  query_var_slug: '',
  menu_position: '',
  show_in_menu: 'true',
  show_in_menu_string: '',
  menu_icon: '',
  supports: [
    'title'
  ],
  taxonomies: [],
  labels: {
    menu_name: '',
    all_items: '',
    add_new: '',
    add_new_item: '',
    edit_item: '',
    new_item: '',
    view_item: '',
    view_items: '',
    search_items: '',
    not_found: '',
    not_found_in_trash: '',
    parent_item_colon: '',
    featured_image: '',
    set_featured_image: '',
    remove_featured_image: '',
    use_featured_image: '',
    archives: '',
    insert_into_item: '',
    uploaded_to_this_item: '',
    filter_items_list: '',
    items_list_navigation: '',
    items_list: '',
    attributes: '',
    name_admin_bar: ''
  },
  custom_supports: ''
})

const taxonomy = ({
  name,
  label,
  singular_label: singular,
  types = []
}) => ({
  name,
  label,
  singular_label: singular,
  description: '',
  public: 'true',
  publicly_queryable: 'true',
  hierarchical: 'false',
  show_ui: 'true',
  show_in_menu: 'true',
  show_in_nav_menus: 'true',
  query_var: 'true',
  query_var_slug: '',
  rewrite: 'true',
  rewrite_slug: '',
  rewrite_withfront: '1',
  rewrite_hierarchical: '0',
  show_admin_column: 'false',
  show_in_rest: 'true',
  show_in_quick_edit: '',
  rest_base: '',
  rest_controller_class: '',
  labels: {
    menu_name: '',
    all_items: '',
    edit_item: '',
    view_item: '',
    update_item: '',
    add_new_item: '',
    new_item_name: '',
    parent_item: '',
    parent_item_colon: '',
    search_items: '',
    popular_items: '',
    separate_items_with_commas: '',
    add_or_remove_items: '',
    choose_from_most_used: '',
    not_found: '',
    no_terms: '',
    items_list_navigation: '',
    items_list: ''
  },
  meta_box_cb: '',
  object_types: types
})

module.exports = {
  post,
  taxonomy
}
