version: 1

pages:
  home:
    options:
      label: Homepage
      path: /
    fields:
      hero:
        title: Text
        subtitle: Text?
      about:
        title: Text
        content: Text
  people:
    options:
      label: People Landing
      path: /people
    fields:
      hero:
        title: Text

posts:
  people:
    options:
      label: People
      singular_label: Person
    fields:
      name:
        first: Text
        middle: Text?
        last: Text
      bio:
        main: Text
        additional: Text?
      email: Text
      phone: Text
  services:
    options:
      label: Services
      singular_label: Service
    fields:
      title: Text